#! /bin/sh

# stop script when an error occurs
set -e

# import .env so we can access DB URL
. "./.env.development.local"

psql $DATABASE_URL -q -f "./database/init.sql"
psql $DATABASE_URL -q -f "./database/locations.sql"
echo "Populated database tables"